name: Hello Actions

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    types: ["closed"]
env:
  name: Raybo
  
jobs:
  build:

    runs-on: ubuntu-latest
    env:
      name: Joe D.
    steps:
    - name: Run a one-line script
      run: |
        echo Hello, $name example!
        echo now multiline- Actor: ${{github.actor}}
        echo Committed by:: ${{github.event.commits[0].author.name}}
      
 dump:
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_CONTEXT: ${{toJson(github)}}
        run: echo "$GITHUB_CONTEXT"
  
        
  pull_requests_only:

    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: build
    steps:
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo Hi, $name.
